workflows:
ios-release:
name: SiiShop iOS Release
max_build_duration: 120

```
environment:
  node: 22
  xcode: latest
  cocoapods: default

scripts:

  - name: Verify folders
    script: |
      pwd
      ls
      ls frontend

  - name: Install frontend dependencies
    script: |
      cd frontend
      npm install

  - name: Verify package scripts
    script: |
      cd frontend
      npm run

  - name: Build Vite production app
    script: |
      cd frontend
      npm run build

  - name: Verify build output
    script: |
      cd frontend
      ls
      ls dist

  - name: Sync Capacitor iOS
    script: |
      cd frontend
      npx cap sync ios

  - name: Verify iOS project
    script: |
      cd frontend/ios/App
      ls

  - name: Install CocoaPods dependencies
    script: |
      cd frontend/ios/App
      pod install

  - name: Build iOS IPA
    script: |
      cd frontend/ios/App

      xcode-project build-ipa \
        --workspace App.xcworkspace \
        --scheme App \
        --archive-flags="-destination generic/platform=iOS"

artifacts:
  - frontend/ios/App/build/ios/ipa/*.ipa
```
